name: Main
on:
  push:
    branches:
      - "main"
permissions:
  contents: read
  pull-requests: write
env:
  ENVIRONMENT: 'development'
  HUMCTL_VERSION: '0.23.2'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: humanitec/setup-cli-action@v1
        with:
          version: ${{ env.HUMCTL_VERSION }}

      # â“ Do we really need that for ghcr??
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push image
        id: build_push
        run: |
          # Make sure repo name is all lowercase for docker push
          # GH_ORG=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
          GH_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')

          #TAG=ghcr.io/$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')/${{ vars.APP_NAME }}:latest
          
          TAG=$GH_REPOSITORY:latest
          echo GH_REPOSITORY: $GH_REPOSITORY
          echo TAG: $TAG

          docker build . --tag $TAG --build-arg GH_REPOSITORY=$GH_REPOSITORY
          docker push $TAG

          echo "IMAGE_TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Deploy Score
        run: |
          humctl score deploy \
              --token ${{ secrets.HUMANITEC_TOKEN }} \
              --org ${{ vars.HUMANITEC_ORG }} \
              --app ${{ vars.APP_NAME }} \
              --env ${{ env.ENVIRONMENT }} \
              -f score.yaml \
              --property "containers.demo.image=${{ steps.build_push.outputs.IMAGE_TAG }}"
